# Generated by Django 5.2.17 on 2026-09-27 08:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('audio', 'Audio'), ('text', 'Text')], max_length=20)),
                ('content_text', models.TextField(blank=True, default='')),
                ('recording_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('processed_duration_seconds', models.FloatField(blank=True, null=True)),
                ('recording_group_id', models.UUIDField(blank=True, null=True)),
                ('intent', models.CharField(blank=True, default='', max_length=32)),
                ('subject', models.CharField(blank=True, default='', max_length=32)),
                ('intent_confidence', models.FloatField(blank=True, null=True)),
                ('subject_confidence', models.FloatField(blank=True, null=True)),
                ('user_asked_for_diary', models.BooleanField(default=False)),
                ('user_asked_for_diary_probability', models.FloatField(blank=True, null=True)),
                ('continues_prior', models.BooleanField(default=False)),
                ('continues_prior_probability', models.FloatField(blank=True, null=True)),
                ('route', models.CharField(blank=True, default='', max_length=32)),
                ('classification_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
                ('usage_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='diary.entry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
