# Generated by Django 5.2.17 on 2026-09-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='entry',
            name='reference_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='item_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('text', 'Text'), ('file', 'File')], max_length=20),
        ),
    ]
