# Generated by Django 5.0.1 on 2026-04-09 14:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingest_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IngestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('gdrive', 'Google Drive'), ('filesystem', 'Filesystem'), ('manual', 'Manual'), ('other', 'Other')], default='manual', max_length=20)),
                ('item_type', models.CharField(choices=[('audio', 'Audio'), ('text', 'Text'), ('email', 'Email'), ('file', 'File'), ('other', 'Other')], default='other', max_length=20)),
                ('template_type', models.CharField(choices=[('plain', 'Plain'), ('list', 'List')], default='plain', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('processed', 'Processed'), ('error', 'Error'), ('tagged', 'Tagged')], default='new', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('external_thread_id', models.CharField(blank=True, max_length=255, null=True)),
                ('source_filename', models.CharField(blank=True, help_text='Original filename when item originates from attachment (e.g. Gmail PDF)', max_length=255, null=True)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content_text', models.TextField(blank=True, default='')),
                ('summary_text', models.TextField(blank=True, default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('audio_duration_seconds', models.FloatField(blank=True, help_text='Original audio duration in seconds', null=True)),
                ('audio_format', models.CharField(blank=True, default='', help_text='Original audio format (webm, wav, mp3)', max_length=20)),
                ('original_file_size', models.BigIntegerField(blank=True, help_text='Original file size in bytes', null=True)),
                ('detected_language', models.CharField(blank=True, default='', help_text='Detected language ISO code', max_length=10)),
                ('audio_deletion_scheduled_at', models.DateTimeField(blank=True, help_text='When the audio file is scheduled for deletion', null=True)),
                ('parent_item', models.ForeignKey(blank=True, help_text='Set when this entry was created as an edited copy of another', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_items', to='ingestion.ingestitem')),
                ('split_parent', models.ForeignKey(blank=True, help_text='Set when this entry was created by splitting a mixed utterance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_children', to='ingestion.ingestitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingest_items', to=settings.AUTH_USER_MODEL)),
                ('ingest_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.ingestrun')),
            ],
        ),
        migrations.CreateModel(
            name='ItemFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('original', 'Original'), ('attachment', 'Attachment'), ('transcript', 'Transcript'), ('processed', 'Processed'), ('thumbnail', 'Thumbnail'), ('export', 'Export'), ('other', 'Other')], default='original', max_length=20)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('storage_url', models.TextField()),
                ('bytes', models.BigIntegerField(blank=True, null=True)),
                ('drive_folder_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ingestion.ingestitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GmailRawMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload_json', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gmail_raw_messages', to=settings.AUTH_USER_MODEL)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_raw', to='ingestion.ingestitem')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='ingestion_g_user_id_b8e405_idx')],
            },
        ),
        migrations.CreateModel(
            name='IngestItemEditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('fields_changed', models.JSONField(default=list)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingest_item_edit_logs', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='ingestion.ingestitem')),
            ],
            options={
                'db_table': 'ingestion_ingestitemeditlog',
                'indexes': [models.Index(fields=['item', 'edited_at'], name='ingestion_i_item_id_8b66cb_idx')],
            },
        ),
        migrations.CreateModel(
            name='IngestJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('fetch_gmail', 'Fetch Gmail message'), ('process_audio', 'Process audio metadata'), ('classify_item', 'Classify item with LLM'), ('parse_calendar', 'Parse calendar event'), ('parse_list', 'Parse item list'), ('parse_financial', 'Parse financial entries'), ('parse_todo', 'Parse to-do items')], max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='queued', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('checkpoint', models.CharField(blank=True, default='', help_text='Current/last completed pipeline step', max_length=50)),
                ('checkpoint_data', models.JSONField(blank=True, default=dict, help_text='Checkpoint state data for resume (e.g., transcription text, chunk paths)')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='ingestion.ingestitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingest_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status', 'job_type'], name='ingestion_i_user_id_10115d_idx'), models.Index(fields=['user', 'queued_at'], name='ingestion_i_user_id_8e08c5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ingestitem',
            index=models.Index(fields=['user', 'occurred_at'], name='ingestion_i_user_id_3d6637_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestitem',
            index=models.Index(fields=['user', 'status'], name='ingestion_i_user_id_31cd88_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestitem',
            index=models.Index(fields=['user', 'item_type'], name='ingestion_i_user_id_9dc730_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestitem',
            index=models.Index(fields=['audio_deletion_scheduled_at'], name='ingestion_i_audio_d_adf316_idx'),
        ),
        migrations.AddConstraint(
            model_name='ingestitem',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('user', 'provider', 'external_id'), name='uniq_user_provider_external_id'),
        ),
        migrations.AddIndex(
            model_name='itemfile',
            index=models.Index(fields=['user', 'role'], name='ingestion_i_user_id_be23b1_idx'),
        ),
        migrations.AddIndex(
            model_name='itemfile',
            index=models.Index(fields=['user', 'created_at'], name='ingestion_i_user_id_45fae7_idx'),
        ),
    ]
