# Generated by Django 5.0.1 on 2026-09-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestitem",
            name="recording_duration_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Original recording duration in whole seconds, before silence removal",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ingestitem",
            name="recording_group_id",
            field=models.UUIDField(
                blank=True,
                help_text="Client-generated id shared by consecutive clips from one recording session",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="ingestitem",
            index=models.Index(
                fields=["user", "recording_group_id"],
                name="ingestion_i_user_id_rgrp_idx",
            ),
        ),
    ]
