# Generated by Django 5.2.17 on 2026-09-28 11:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diary', '0004_entry_reference_entry_reference_confidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_name', models.CharField(blank=True, default='', max_length=255)),
                ('record_context', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('llm_response', models.JSONField(blank=True, default=dict)),
                ('external_id', models.CharField(blank=True, default='', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_records', to='diary.entry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_index', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], default='expense', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('merchant', models.CharField(blank=True, default='', max_length=255)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('payment_method', models.CharField(blank=True, default='', max_length=50)),
                ('financial_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.financialrecord')),
            ],
            options={
                'ordering': ['item_index'],
            },
        ),
        migrations.AddConstraint(
            model_name='financialrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('user', 'external_id'), name='uniq_user_finance_external_id'),
        ),
        migrations.AddConstraint(
            model_name='financialitem',
            constraint=models.UniqueConstraint(fields=('financial_record', 'item_index'), name='uniq_finance_record_item_index'),
        ),
    ]
