# Generated by Django 5.0.1 on 2026-04-09 14:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTriageResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_route', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('contains_time_reference', models.BooleanField(default=False)),
                ('contains_multiple_items', models.BooleanField(default=False)),
                ('raw_output', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage_result', to='ingestion.ingestitem')),
            ],
            options={
                'indexes': [models.Index(fields=['primary_route'], name='intent_rout_primary_dcb43f_idx'), models.Index(fields=['is_deleted'], name='intent_rout_is_dele_f563fd_idx')],
            },
        ),
    ]
