# Generated by Django 5.2.17 on 2026-09-28 11:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diary', '0004_entry_reference_entry_reference_confidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_index', models.PositiveIntegerField()),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, default='Europe/Lisbon', max_length=64)),
                ('status', models.CharField(choices=[('inserted', 'Inserted'), ('taken', 'Taken'), ('failed', 'Failed')], max_length=16)),
                ('problem', models.TextField(blank=True, default='')),
                ('google_event_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_bookings', to='diary.entry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event_index', 'created_at'],
            },
        ),
    ]
