# Generated by Django 5.0.1 on 2026-04-09 14:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_name', models.CharField(blank=True, default='', help_text="Inferred record name (e.g. 'Despesas de hoje')", max_length=255)),
                ('record_context', models.TextField(blank=True, default='', help_text="Optional context (e.g. 'viagem a Paris')")),
                ('llm_response', models.JSONField(blank=True, default=dict, help_text='Raw LLM extraction response')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_financial_records', to=settings.AUTH_USER_MODEL)),
                ('source_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='ingestion.ingestitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_index', models.PositiveSmallIntegerField(default=0, help_text='Order within the record (0-based)')),
                ('type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], default='expense', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount (positive)', max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('merchant', models.CharField(blank=True, default='', max_length=255)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('payment_method', models.CharField(blank=True, default='', max_length=50)),
                ('item_data', models.JSONField(blank=True, default=dict, help_text='Full item dict from LLM (for extensibility)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('financial_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='financial_parser.financialrecord')),
            ],
            options={
                'ordering': ['financial_record', 'item_index'],
            },
        ),
        migrations.CreateModel(
            name='HypermarketLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_index', models.PositiveSmallIntegerField(default=0, help_text='Order within the invoice (0-based)')),
                ('description', models.TextField(blank=True, default='', help_text='Product name/description')),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('gmail_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('gmail_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('financial_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hypermarket_line_items', to='financial_parser.financialrecord')),
            ],
            options={
                'ordering': ['financial_record', 'line_index'],
            },
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['user', 'status'], name='financial_p_user_id_61f687_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['user', 'created_at'], name='financial_p_user_id_11e063_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['source_item'], name='financial_p_source__805cd2_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['user', 'is_deleted'], name='financial_p_user_id_29bbe4_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'success'), ('source_item__isnull', False)), fields=('user', 'source_item'), name='uniq_user_source_item_financial_record_notnull'),
        ),
        migrations.AddIndex(
            model_name='financialitem',
            index=models.Index(fields=['financial_record', 'item_index'], name='financial_p_financi_6b727f_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialitem',
            constraint=models.UniqueConstraint(fields=('financial_record', 'item_index'), name='uniq_financial_record_item_index'),
        ),
        migrations.AddIndex(
            model_name='hypermarketlineitem',
            index=models.Index(fields=['financial_record', 'line_index'], name='financial_p_financi_ea893f_idx'),
        ),
        migrations.AddConstraint(
            model_name='hypermarketlineitem',
            constraint=models.UniqueConstraint(fields=('financial_record', 'line_index'), name='uniq_hypermarket_financial_record_line_index'),
        ),
    ]
