# Generated by Django 5.0.1 on 2026-04-09 14:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchCalendarRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_text', models.TextField(help_text='Original user input text')),
                ('parsed_events_json', models.JSONField(blank=True, default=list, help_text='Raw LLM response: list of event dicts in Google Calendar format')),
                ('error_message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('partial', 'Partial')], default='pending', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingest_item', models.ForeignKey(blank=True, help_text='IngestItem that triggered this batch (when from pipeline)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_calendar_requests', to='ingestion.ingestitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_calendar_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BatchCalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_index', models.PositiveSmallIntegerField(default=0, help_text='Order of this event within the batch (0-based)')),
                ('event_data', models.JSONField(default=dict, help_text='Full event in Google Calendar API format')),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('google_event_id', models.CharField(blank=True, default='', max_length=255)),
                ('html_link', models.URLField(blank=True, default='')),
                ('api_response', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pending_confirmation', 'Pending Confirmation'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped')], default='pending', max_length=24)),
                ('error_message', models.TextField(blank=True, default='')),
                ('conflicting_events', models.JSONField(blank=True, default=list)),
                ('alternative_slots', models.JSONField(blank=True, default=list)),
                ('alternative_slots_by_day', models.JSONField(blank=True, default=list, help_text='Slots grouped by day for day-navigation UI')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='batch_calendar.batchcalendarrequest')),
            ],
            options={
                'ordering': ['batch_request', 'event_index'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_event_id', models.CharField(blank=True, default='', max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=500)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('html_link', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('pending_confirmation', 'Pending Confirmation'), ('cancelled', 'Cancelled'), ('conflicted', 'Conflicted')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('llm_response', models.JSONField(blank=True, default=dict)),
                ('api_response', models.JSONField(blank=True, default=dict)),
                ('conflicting_events', models.JSONField(blank=True, default=list)),
                ('alternative_slots', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('replaces_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='batch_calendar.calendarevent')),
                ('source_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='ingestion.ingestitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calendar_parser_calendarevent',
            },
        ),
        migrations.CreateModel(
            name='CalendarWatchChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=64, unique=True)),
                ('resource_id', models.CharField(blank=True, default='', max_length=255)),
                ('calendar_id', models.CharField(default='primary', max_length=255)),
                ('sync_token', models.CharField(blank=True, default='', max_length=512)),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_watch_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calendar_parser_calendarwatchchannel',
            },
        ),
        migrations.AddIndex(
            model_name='batchcalendarrequest',
            index=models.Index(fields=['user', 'status'], name='batch_calen_user_id_8c2efc_idx'),
        ),
        migrations.AddIndex(
            model_name='batchcalendarrequest',
            index=models.Index(fields=['user', 'is_deleted'], name='batch_calen_user_id_f3970c_idx'),
        ),
        migrations.AddIndex(
            model_name='batchcalendarrequest',
            index=models.Index(fields=['user', 'created_at'], name='batch_calen_user_id_3edc17_idx'),
        ),
        migrations.AddIndex(
            model_name='batchcalendarrequest',
            index=models.Index(fields=['ingest_item'], name='batch_calen_ingest__4e9361_idx'),
        ),
        migrations.AddIndex(
            model_name='batchcalendarevent',
            index=models.Index(fields=['batch_request', 'event_index'], name='batch_calen_batch_r_d6621f_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['user', 'status'], name='calendar_pa_user_id_7760eb_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['user', 'created_at'], name='calendar_pa_user_id_4dee84_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['source_item'], name='calendar_pa_source__d85d65_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['user', 'is_deleted'], name='calendar_pa_user_id_d4a760_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarevent',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'success')), fields=('user', 'source_item'), name='uniq_user_source_item_calendar_event_success'),
        ),
        migrations.AddIndex(
            model_name='calendarwatchchannel',
            index=models.Index(fields=['channel_id'], name='calendar_pa_channel_82a1ca_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarwatchchannel',
            index=models.Index(fields=['user', 'is_active'], name='calendar_pa_user_id_70ad28_idx'),
        ),
    ]
