# Generated by Django 5.0.1 on 2026-04-09 14:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Canonical name used in LLM output and stored in ListItem.unit', max_length=30, unique=True)),
                ('display_name', models.CharField(blank=True, default='', help_text='Human-friendly label (optional)', max_length=60)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='List of alternative spellings, e.g. ["quilo","quilos","kilogram"]')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ListRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('list_name', models.CharField(blank=True, default='', help_text="Inferred list name (e.g. 'compras' from 'lista de compras')", max_length=255)),
                ('list_context', models.TextField(blank=True, default='', help_text="Optional context/occasion for the list (e.g. John's birthday party)")),
                ('llm_response', models.JSONField(blank=True, default=dict, help_text='Raw LLM extraction response')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_list_records', to=settings.AUTH_USER_MODEL)),
                ('source_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_records', to='ingestion.ingestitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='list_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_index', models.PositiveSmallIntegerField(default=0, help_text='Order of this item within the list or within parent (0-based)')),
                ('text', models.TextField(help_text='Primary item content')),
                ('description', models.TextField(blank=True, default='', help_text='Optional extra detail')),
                ('due_date', models.DateField(blank=True, help_text='Optional due date', null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Optional quantity (e.g. 2, 1.5) when mentioned in the source text', max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, default='', help_text='Optional unit (e.g. kg, litre, unit) when mentioned in the source text', max_length=30)),
                ('item_data', models.JSONField(blank=True, default=dict, help_text='Full item dict from LLM (for extensibility)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent item for sublist entries (null for top-level)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='list_parser.listitem')),
                ('list_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='list_parser.listrecord')),
            ],
            options={
                'ordering': ['list_record', 'item_index'],
            },
        ),
        migrations.AddIndex(
            model_name='listrecord',
            index=models.Index(fields=['user', 'status'], name='list_parser_user_id_ee6d8a_idx'),
        ),
        migrations.AddIndex(
            model_name='listrecord',
            index=models.Index(fields=['user', 'created_at'], name='list_parser_user_id_2b158d_idx'),
        ),
        migrations.AddIndex(
            model_name='listrecord',
            index=models.Index(fields=['source_item'], name='list_parser_source__c16ce0_idx'),
        ),
        migrations.AddIndex(
            model_name='listrecord',
            index=models.Index(fields=['user', 'is_deleted'], name='list_parser_user_id_78ed4d_idx'),
        ),
        migrations.AddConstraint(
            model_name='listrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'success'), ('source_item__isnull', False)), fields=('user', 'source_item'), name='uniq_user_source_item_list_record_notnull'),
        ),
        migrations.AddIndex(
            model_name='listitem',
            index=models.Index(fields=['list_record', 'parent', 'item_index'], name='list_parser_list_re_e28d14_idx'),
        ),
        migrations.AddConstraint(
            model_name='listitem',
            constraint=models.UniqueConstraint(fields=('list_record', 'parent', 'item_index'), name='uniq_list_record_parent_item_index'),
        ),
    ]
