# Generated by Django 5.2.17 on 2026-09-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textrewrite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewriteusage',
            name='style',
            field=models.CharField(default='grammar', max_length=32),
        ),
    ]
