# Generated by Django 5.0.1 on 2026-04-09 14:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classification', '0001_initial'),
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_name', models.CharField(blank=True, default='', max_length=255)),
                ('record_context', models.TextField(blank=True, default='')),
                ('llm_response', models.JSONField(blank=True, default=dict, help_text='Raw LLM extraction response')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todo_records', to=settings.AUTH_USER_MODEL)),
                ('source_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todorecord_records', to='ingestion.ingestitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_index', models.PositiveSmallIntegerField(default=0, help_text='Order of this item within the record (0-based)')),
                ('text', models.TextField(blank=True, default='', help_text='Primary item content')),
                ('description', models.TextField(blank=True, default='', help_text='Optional extra detail')),
                ('item_data', models.JSONField(blank=True, default=dict, help_text='Full item dict from LLM (for extensibility)')),
                ('entity_name', models.CharField(blank=True, default='', help_text='Denormalized entity display name for search/display', max_length=255)),
                ('entity_type', models.CharField(blank=True, default='', help_text='Denormalized entity type (PERSON, VENDOR, ORGANIZATION, etc.)', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('priority', models.IntegerField(choices=[(1, 'Lowest'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Urgent')], default=3)),
                ('completion_status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, help_text='Optional due date', null=True)),
                ('due_time', models.TimeField(blank=True, help_text='Optional due time', null=True)),
                ('topic', models.CharField(blank=True, default='', help_text='Topic category (mapped from taxonomy subject key)', max_length=255)),
                ('subtopic', models.CharField(blank=True, default='', help_text='Finer granularity within topic', max_length=255)),
                ('recurrence_rule', models.CharField(blank=True, default='', help_text='Recurrence pattern: daily, weekly, monthly, or empty', max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('entity', models.ForeignKey(blank=True, help_text='Primary associated entity (person, vendor, org, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_items', to='classification.entitycatalog')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent item for subtask entries (null for top-level)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='managed_lists.todoitem')),
                ('todo_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='managed_lists.todorecord')),
            ],
            options={
                'ordering': ['todo_record', 'item_index'],
            },
        ),
        migrations.CreateModel(
            name='ManagedListProjection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('list_type', models.CharField(choices=[('shopping', 'Shopping'), ('todo', 'To-Do'), ('financial', 'Financial'), ('contact', 'Contact'), ('general', 'General')], max_length=20)),
                ('record_id', models.UUIDField(help_text='PK of the concrete record (TodoRecord, ListRecord, etc.)')),
                ('item_id', models.UUIDField(help_text='PK of the concrete item (TodoItem, ListItem, etc.)')),
                ('title', models.TextField(blank=True, default='', help_text='Primary text/name')),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', help_text='Maps to: list_name, financial category, topic', max_length=255)),
                ('topic', models.CharField(blank=True, default='', max_length=255)),
                ('subtopic', models.CharField(blank=True, default='', max_length=255)),
                ('item_status', models.CharField(blank=True, default='', help_text='open, done, expense, income, etc.', max_length=30)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=30)),
                ('entity_name', models.CharField(blank=True, default='', help_text='e.g. Zara, Dr. Silva, João', max_length=255)),
                ('entity_type', models.CharField(blank=True, default='', help_text='PERSON, VENDOR, ORGANIZATION, etc.', max_length=30)),
                ('entity_catalog_id', models.UUIDField(blank=True, help_text='FK value for drill-down if needed', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_ingest_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_list_projections', to='ingestion.ingestitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_list_projections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'list_type'], name='managed_lis_user_id_b5d6a5_idx'), models.Index(fields=['user', 'topic', 'subtopic'], name='managed_lis_user_id_2b951d_idx'), models.Index(fields=['user', 'item_status'], name='managed_lis_user_id_1fa71d_idx'), models.Index(fields=['user', 'due_date'], name='managed_lis_user_id_fba430_idx'), models.Index(fields=['user', 'entity_type'], name='managed_lis_user_id_ad0c12_idx'), models.Index(fields=['user', 'entity_name'], name='managed_lis_user_id_996cc3_idx'), models.Index(fields=['record_id'], name='managed_lis_record__ead902_idx'), models.Index(fields=['item_id'], name='managed_lis_item_id_be854a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='todorecord',
            index=models.Index(fields=['user', 'status'], name='managed_lis_user_id_c6aa11_idx'),
        ),
        migrations.AddIndex(
            model_name='todorecord',
            index=models.Index(fields=['user', 'created_at'], name='managed_lis_user_id_0f856c_idx'),
        ),
        migrations.AddIndex(
            model_name='todorecord',
            index=models.Index(fields=['source_item'], name='managed_lis_source__cae83b_idx'),
        ),
        migrations.AddIndex(
            model_name='todorecord',
            index=models.Index(fields=['user', 'is_deleted'], name='managed_lis_user_id_959a1c_idx'),
        ),
        migrations.AddConstraint(
            model_name='todorecord',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'success')), fields=('user', 'source_item'), name='uniq_user_source_item_todo_record_success'),
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['todo_record', 'parent', 'item_index'], name='managed_lis_todo_re_1c5f03_idx'),
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['completion_status'], name='managed_lis_complet_2056fe_idx'),
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['priority'], name='managed_lis_priorit_3a0202_idx'),
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['due_date'], name='managed_lis_due_dat_b4f167_idx'),
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['topic', 'subtopic'], name='managed_lis_topic_91aaa7_idx'),
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['entity_type'], name='managed_lis_entity__ac8523_idx'),
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['is_deleted'], name='managed_lis_is_dele_10673c_idx'),
        ),
        migrations.AddConstraint(
            model_name='todoitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('todo_record', 'parent', 'item_index'), name='uniq_todo_record_parent_item_index'),
        ),
    ]
