# Generated by Django 5.0.1 on 2026-04-09 14:35

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classification', '0001_initial'),
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('source_entries', models.TextField(blank=True, default='')),
                ('sequence_index', models.IntegerField()),
                ('status', models.CharField(choices=[('read', 'Read'), ('unread', 'Unread')], default='read', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_messages', to='retrieval.chatsession')),
            ],
            options={
                'ordering': ['sequence_index'],
            },
        ),
        migrations.CreateModel(
            name='UserChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('sequence_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to='retrieval.chatsession')),
            ],
            options={
                'ordering': ['sequence_index'],
            },
        ),
        migrations.CreateModel(
            name='ItemRetrievalProjection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_subject_key', models.TextField(blank=True, default='')),
                ('secondary_subject_keys', models.JSONField(blank=True, default=list)),
                ('primary_intent_key', models.TextField(blank=True, default='')),
                ('secondary_intent_keys', models.JSONField(blank=True, default=list)),
                ('primary_context_key', models.TextField(blank=True, default='')),
                ('secondary_context_keys', models.JSONField(blank=True, default=list)),
                ('time_keys', models.JSONField(blank=True, default=list)),
                ('governance_key', models.TextField(blank=True, default='')),
                ('entity_ids', models.JSONField(blank=True, default=list)),
                ('entity_names_normalized', models.TextField(blank=True, default='')),
                ('entity_roles', models.TextField(blank=True, default='')),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(blank=True, null=True)),
                ('detected_language', models.CharField(blank=True, default='', max_length=10)),
                ('content_text_searchable', models.TextField(blank=True, default='')),
                ('summary_text_searchable', models.TextField(blank=True, default='')),
                ('embedding_ready_text', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('keywords', models.TextField(blank=True, default='')),
                ('list_items_flat', models.TextField(blank=True, default='')),
                ('financial_items_flat', models.TextField(blank=True, default='')),
                ('todo_items_flat', models.TextField(blank=True, default='')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('token_index', models.JSONField(blank=True, default=list)),
                ('has_attachment', models.BooleanField(default=False)),
                ('attachment_types', models.JSONField(blank=True, default=list)),
                ('overall_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('is_actionable', models.BooleanField(default=False)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('last_classified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingest_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retrieval_projection', to='ingestion.ingestitem')),
                ('latest_classification_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='classification.itemclassificationrun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieval_projections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'item retrieval projections',
                'indexes': [models.Index(fields=['user', 'primary_subject_key'], name='idx_proj_subject'), models.Index(fields=['user', 'primary_intent_key'], name='idx_proj_intent'), models.Index(fields=['user', 'primary_context_key'], name='idx_proj_context'), models.Index(fields=['user', 'governance_key'], name='idx_proj_governance'), models.Index(fields=['user', 'occurred_at'], name='idx_proj_user_date')],
            },
        ),
    ]
