# Generated by Django 5.2.17 on 2026-09-27 14:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('complete', 'Complete')], default='open', max_length=16)),
                ('content_text', models.TextField(blank=True, default='')),
                ('total_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('content_text', models.TextField(blank=True, default='')),
                ('transcription_error', models.TextField(blank=True, default='')),
                ('recording_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('processed_duration_seconds', models.FloatField(blank=True, null=True)),
                ('relative_path', models.CharField(max_length=500)),
                ('processed_relative_path', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='conference.conference')),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('conference', 'sequence'), name='uniq_conference_segment_sequence')],
            },
        ),
    ]
