# Generated by Django 5.0.1 on 2026-04-09 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('person', 'Person'), ('organization', 'Organization'), ('project', 'Project'), ('location', 'Location'), ('device', 'Device'), ('account', 'Account'), ('document', 'Document'), ('product', 'Product'), ('contact', 'Contact'), ('vendor', 'Vendor'), ('client', 'Client'), ('unknown', 'Unknown')], max_length=20)),
                ('canonical_name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(max_length=255)),
                ('external_ref', models.CharField(blank=True, default='', max_length=255)),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_catalog', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'entity catalog entries',
            },
        ),
        migrations.CreateModel(
            name='ItemClassificationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('taxonomy_pack_used', models.CharField(choices=[('shared', 'Shared'), ('personal', 'Personal'), ('enterprise', 'Enterprise')], max_length=20)),
                ('classifier_version', models.CharField(max_length=60)),
                ('prompt_version', models.CharField(max_length=60)),
                ('verifier_version', models.CharField(blank=True, default='', max_length=60)),
                ('verifier_prompt_version', models.CharField(blank=True, default='', max_length=60)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('error', 'Error')], default='pending', max_length=20)),
                ('raw_model_output_json', models.JSONField(blank=True, null=True)),
                ('raw_verifier_output_json', models.JSONField(blank=True, null=True)),
                ('reasoning_text', models.TextField(blank=True, default='')),
                ('verifier_reasoning_text', models.TextField(blank=True, default='')),
                ('overall_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('verifier_overall_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('has_ambiguity', models.BooleanField(default=False)),
                ('ambiguity_notes', models.JSONField(blank=True, null=True)),
                ('validation_errors_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ingest_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_runs', to='ingestion.ingestitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemEntityLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('person', 'Person'), ('organization', 'Organization'), ('project', 'Project'), ('location', 'Location'), ('device', 'Device'), ('account', 'Account'), ('document', 'Document'), ('product', 'Product'), ('contact', 'Contact'), ('vendor', 'Vendor'), ('client', 'Client'), ('unknown', 'Unknown')], max_length=20)),
                ('raw_mention', models.TextField()),
                ('normalized_mention', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, default='', max_length=60)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('classification_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_links', to='classification.itemclassificationrun')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_links', to='classification.entitycatalog')),
                ('ingest_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_links', to='ingestion.ingestitem')),
            ],
        ),
        migrations.CreateModel(
            name='TaxonomyNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('taxonomy_pack', models.CharField(choices=[('shared', 'Shared'), ('personal', 'Personal'), ('enterprise', 'Enterprise')], max_length=20)),
                ('dimension', models.CharField(choices=[('subject', 'Subject'), ('intent', 'Intent'), ('context', 'Context'), ('time', 'Time'), ('governance', 'Governance')], max_length=20)),
                ('level', models.SmallIntegerField(help_text='Depth 1-4 in the hierarchy')),
                ('key', models.TextField(help_text='Dotted machine-facing path, e.g. personal.health.appointment.dentist')),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('is_leaf', models.BooleanField(default=False)),
                ('is_selectable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='classification.taxonomynode')),
            ],
            options={
                'ordering': ['dimension', 'sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='TaxonomyClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.IntegerField()),
                ('ancestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descendant_links', to='classification.taxonomynode')),
                ('descendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancestor_links', to='classification.taxonomynode')),
            ],
        ),
        migrations.CreateModel(
            name='TaxonomyAllowedCombination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_allowed', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='classification.taxonomynode')),
                ('governance_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='classification.taxonomynode')),
                ('intent_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='classification.taxonomynode')),
                ('subject_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='classification.taxonomynode')),
                ('time_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='classification.taxonomynode')),
            ],
            options={
                'verbose_name_plural': 'taxonomy allowed combinations',
            },
        ),
        migrations.CreateModel(
            name='ItemClassificationSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dimension', models.CharField(choices=[('subject', 'Subject'), ('intent', 'Intent'), ('context', 'Context'), ('time', 'Time'), ('governance', 'Governance')], max_length=20)),
                ('path_key', models.TextField(help_text='Denormalized copy of taxonomy_node.key')),
                ('is_primary', models.BooleanField(default=False)),
                ('rank_order', models.SmallIntegerField(default=1)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('selection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('classification_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='classification.itemclassificationrun')),
                ('ingest_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_selections', to='ingestion.ingestitem')),
                ('taxonomy_node', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='selections', to='classification.taxonomynode')),
            ],
        ),
        migrations.CreateModel(
            name='TaxonomyParserRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dimension_match', models.CharField(choices=[('subject', 'Subject'), ('intent', 'Intent'), ('context', 'Context'), ('time', 'Time'), ('governance', 'Governance')], help_text='Which dimension this route matches on', max_length=20)),
                ('key_pattern', models.CharField(help_text="Taxonomy key or prefix pattern (e.g. 'intent.reminder.*')", max_length=255)),
                ('parser_action', models.CharField(help_text='Downstream parser: calendar, list, financial', max_length=40)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority wins when multiple routes match')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxonomy_node', models.ForeignKey(blank=True, help_text='Optional direct FK; key_pattern is the primary match field', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parser_routes', to='classification.taxonomynode')),
            ],
            options={
                'ordering': ['-priority', 'key_pattern'],
            },
        ),
        migrations.CreateModel(
            name='TaxonomyPermissionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_scope', models.CharField(help_text='e.g. self_only, team_only, management_only, shared_household', max_length=60)),
                ('encryption_policy', models.CharField(help_text='e.g. user_key, tenant_key, server_key_plus_rbac', max_length=60)),
                ('retention_policy', models.CharField(help_text='e.g. keep, ephemeral_30d, legal_hold, archive_7y', max_length=60)),
                ('visibility_rule', models.CharField(help_text='e.g. hidden_by_default, searchable, restricted_searchable', max_length=60)),
                ('requires_elevated_access', models.BooleanField(default=False)),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxonomy_node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permission_policy', to='classification.taxonomynode')),
            ],
            options={
                'verbose_name_plural': 'taxonomy permission policies',
            },
        ),
        migrations.AddIndex(
            model_name='entitycatalog',
            index=models.Index(fields=['user', 'entity_type', 'normalized_name'], name='idx_entity_catalog_lookup'),
        ),
        migrations.AddConstraint(
            model_name='entitycatalog',
            constraint=models.UniqueConstraint(fields=('user', 'entity_type', 'normalized_name'), name='uq_entity_catalog'),
        ),
        migrations.AddIndex(
            model_name='itemclassificationrun',
            index=models.Index(fields=['ingest_item', '-created_at'], name='idx_classrun_item_date'),
        ),
        migrations.AddIndex(
            model_name='itemclassificationrun',
            index=models.Index(fields=['is_deleted'], name='idx_classrun_is_deleted'),
        ),
        migrations.AddIndex(
            model_name='itementitylink',
            index=models.Index(fields=['ingest_item'], name='idx_entitylink_item'),
        ),
        migrations.AddIndex(
            model_name='itementitylink',
            index=models.Index(fields=['is_deleted'], name='idx_entitylink_is_deleted'),
        ),
        migrations.AddIndex(
            model_name='taxonomynode',
            index=models.Index(fields=['taxonomy_pack', 'dimension', 'key'], name='idx_taxonomy_node_lookup'),
        ),
        migrations.AddConstraint(
            model_name='taxonomynode',
            constraint=models.UniqueConstraint(fields=('key',), name='uq_taxonomy_node_key'),
        ),
        migrations.AddConstraint(
            model_name='taxonomynode',
            constraint=models.CheckConstraint(check=models.Q(('level__gte', 1), ('level__lte', 4)), name='chk_taxonomy_level'),
        ),
        migrations.AddConstraint(
            model_name='taxonomyclosure',
            constraint=models.UniqueConstraint(fields=('ancestor', 'descendant'), name='uq_taxonomy_closure'),
        ),
        migrations.AddConstraint(
            model_name='taxonomyclosure',
            constraint=models.CheckConstraint(check=models.Q(('depth__gte', 0)), name='chk_closure_depth'),
        ),
        migrations.AddIndex(
            model_name='itemclassificationselection',
            index=models.Index(fields=['ingest_item', 'dimension', 'is_primary', 'rank_order'], name='idx_classselection_item_dim'),
        ),
        migrations.AddIndex(
            model_name='itemclassificationselection',
            index=models.Index(fields=['is_deleted'], name='idx_classselection_is_deleted'),
        ),
        migrations.AddConstraint(
            model_name='itemclassificationselection',
            constraint=models.UniqueConstraint(fields=('classification_run', 'dimension', 'taxonomy_node', 'rank_order'), name='uq_classselection_run_dim_node_rank'),
        ),
        migrations.AddIndex(
            model_name='taxonomyparserroute',
            index=models.Index(fields=['dimension_match', 'is_active'], name='idx_parserroute_dim_active'),
        ),
    ]
