# Generated by Django 5.0.1 on 2026-04-09 14:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(help_text='Service name: whisper, gpt-4o-mini, etc.', max_length=50)),
                ('usage_type', models.CharField(help_text='Usage type: audio_minutes, input_tokens, output_tokens', max_length=50)),
                ('amount', models.DecimalField(decimal_places=4, help_text='Usage amount', max_digits=10)),
                ('origin', models.CharField(blank=True, help_text='Originating function name, e.g. process_audio_ingest', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'API usage log',
                'verbose_name_plural': 'API usage logs',
                'db_table': 'accounts_apiusagelog',
            },
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Setting key (e.g., recorder.max_duration)', max_length=100, unique=True)),
                ('value', models.JSONField(help_text='Setting value (any JSON type)')),
                ('description', models.TextField(blank=True, help_text='Description of this setting')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'global setting',
                'verbose_name_plural': 'global settings',
                'db_table': 'accounts_globalsettings',
            },
        ),
        migrations.CreateModel(
            name='UserFeatureConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_auto_classification', models.BooleanField(default=True, help_text='Automatically classify items after processing')),
                ('enable_calendar_integration', models.BooleanField(default=True, help_text='Enable automatic Google Calendar event creation')),
                ('calendar_trigger_tags', models.JSONField(blank=True, default=list, help_text='Tag names that trigger calendar parsing')),
                ('default_calendar_id', models.CharField(default='primary', help_text='Google Calendar ID for event creation', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user feature config',
                'verbose_name_plural': 'user feature configs',
                'db_table': 'accounts_userfeatureconfig',
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language', models.CharField(default='en', help_text='Preferred language for translations (ISO 639-1 code)', max_length=50)),
                ('audio_retention_days', models.PositiveIntegerField(default=7, help_text='Days to keep original audio files (0 = delete immediately after processing)')),
                ('enable_translation', models.BooleanField(default=True, help_text='If True, translate diary content to preferred language when detected language differs')),
                ('onboarding_completed', models.BooleanField(default=False, help_text='Whether user has completed initial onboarding')),
                ('dark_mode', models.BooleanField(default=True, help_text='Whether dark mode is enabled')),
                ('accent_theme', models.CharField(choices=[('green', 'Green'), ('blue', 'Blue'), ('indigo', 'Indigo'), ('purple', 'Purple'), ('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow')], default='green', help_text='Selected accent color theme', max_length=10)),
                ('standalone_app_ui', models.BooleanField(default=True, help_text='If True, use app-like mode (hide browser address bar) when added to home screen')),
                ('show_recording_timer', models.BooleanField(default=True, help_text='Whether to show the recording duration timer during recording')),
                ('transcription_text_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='small', help_text='Font size for transcriptions and diary entries (small=14px, medium=16px, large=18px)', max_length=10)),
                ('interface_language', models.CharField(default='pt-pt', help_text='Interface language for viewing pages (e.g. pt-pt, en). Persists across browser clears.', max_length=10)),
                ('drive_attachment_folder_name', models.CharField(blank=True, default='VoiceDiaryFiles/attachments', help_text='Google Drive folder path for attachments (e.g. VoiceDiaryFiles/attachments). Files are uploaded into this folder.', max_length=255)),
                ('drive_attachment_folder_id', models.CharField(blank=True, help_text='Google Drive folder ID of the leaf folder; set when folder is first created or resolved.', max_length=128, null=True)),
                ('timezone', models.CharField(choices=[('Europe/Lisbon', 'Lisbon (Portugal, UTC+0/+1)'), ('Europe/London', 'London (UK, UTC+0/+1)'), ('Europe/Paris', 'Paris (France, UTC+1/+2)'), ('Europe/Berlin', 'Berlin (Germany, UTC+1/+2)'), ('Europe/Madrid', 'Madrid (Spain, UTC+1/+2)'), ('Europe/Rome', 'Rome (Italy, UTC+1/+2)'), ('Europe/Amsterdam', 'Amsterdam (Netherlands, UTC+1/+2)'), ('Europe/Brussels', 'Brussels (Belgium, UTC+1/+2)'), ('Europe/Vienna', 'Vienna (Austria, UTC+1/+2)'), ('Europe/Zurich', 'Zurich (Switzerland, UTC+1/+2)'), ('Europe/Stockholm', 'Stockholm (Sweden, UTC+1/+2)'), ('Europe/Oslo', 'Oslo (Norway, UTC+1/+2)'), ('Europe/Copenhagen', 'Copenhagen (Denmark, UTC+1/+2)'), ('Europe/Helsinki', 'Helsinki (Finland, UTC+2/+3)'), ('Europe/Warsaw', 'Warsaw (Poland, UTC+1/+2)'), ('Europe/Prague', 'Prague (Czech Republic, UTC+1/+2)'), ('Europe/Budapest', 'Budapest (Hungary, UTC+1/+2)'), ('Europe/Bucharest', 'Bucharest (Romania, UTC+2/+3)'), ('Europe/Athens', 'Athens (Greece, UTC+2/+3)'), ('Europe/Istanbul', 'Istanbul (Turkey, UTC+3)'), ('Europe/Moscow', 'Moscow (Russia, UTC+3)'), ('America/New_York', 'New York (UTC-5/-4)'), ('America/Chicago', 'Chicago (UTC-6/-5)'), ('America/Denver', 'Denver (UTC-7/-6)'), ('America/Los_Angeles', 'Los Angeles (UTC-8/-7)'), ('America/Toronto', 'Toronto (UTC-5/-4)'), ('America/Vancouver', 'Vancouver (UTC-8/-7)'), ('America/Sao_Paulo', 'São Paulo (UTC-3)'), ('America/Buenos_Aires', 'Buenos Aires (UTC-3)'), ('America/Mexico_City', 'Mexico City (UTC-6/-5)'), ('Asia/Dubai', 'Dubai (UTC+4)'), ('Asia/Kolkata', 'Mumbai/Kolkata (UTC+5:30)'), ('Asia/Singapore', 'Singapore (UTC+8)'), ('Asia/Tokyo', 'Tokyo (UTC+9)'), ('Asia/Seoul', 'Seoul (UTC+9)'), ('Asia/Shanghai', 'Shanghai (UTC+8)'), ('Asia/Hong_Kong', 'Hong Kong (UTC+8)'), ('Asia/Jakarta', 'Jakarta (UTC+7)'), ('Australia/Sydney', 'Sydney (UTC+10/+11)'), ('Pacific/Auckland', 'Auckland (UTC+12/+13)'), ('Africa/Johannesburg', 'Johannesburg (UTC+2)'), ('Africa/Lagos', 'Lagos (UTC+1)'), ('Africa/Cairo', 'Cairo (UTC+2)'), ('Africa/Nairobi', 'Nairobi (UTC+3)'), ('UTC', 'UTC')], default='Europe/Lisbon', help_text='User timezone, used for calendar event scheduling.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user preferences',
                'verbose_name_plural': 'user preferences',
                'db_table': 'accounts_userpreferences',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='User bio (optional)', max_length=500)),
                ('phone_number', models.CharField(blank=True, help_text='User phone number (optional)', max_length=20)),
                ('location', models.CharField(blank=True, help_text='User location (optional)', max_length=100)),
                ('website', models.URLField(blank=True, help_text='User website (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
                'db_table': 'accounts_userprofile',
            },
        ),
        migrations.CreateModel(
            name='UserSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_google_access_token', models.TextField(blank=True, help_text='Encrypted Google OAuth access token', null=True)),
                ('encrypted_google_refresh_token', models.TextField(blank=True, help_text='Encrypted Google OAuth refresh token', null=True)),
                ('encrypted_google_token_expiry', models.TextField(blank=True, help_text='Encrypted token expiry timestamp (ISO format)', null=True)),
                ('google_token_scopes', models.TextField(blank=True, help_text='JSON array of granted Google OAuth scopes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user secret',
                'verbose_name_plural': 'user secrets',
                'db_table': 'accounts_usersecret',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='User must provide a valid, unique email address.', max_length=255, unique=True, verbose_name='email address')),
                ('profile_picture', models.ImageField(blank=True, help_text='User profile picture (optional)', null=True, upload_to='profile_pictures/')),
                ('is_email_verified', models.BooleanField(default=False, help_text='Whether user has verified their email address')),
                ('email_verification_token', models.CharField(blank=True, help_text='Token for email verification', max_length=100, null=True, unique=True)),
                ('is_google_account', models.BooleanField(default=False, help_text='Whether user registered via Google OAuth')),
                ('deletion_requested_at', models.DateTimeField(blank=True, help_text='When user requested account deletion; null if not requested', null=True)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('ultra', 'Ultra')], default='free', help_text='Plan tier (free / pro / ultra); affects rate limits such as transcription.', max_length=10)),
                ('is_test_user', models.BooleanField(default=False, help_text='Test user: bypasses all quota and feature restrictions. Set manually via admin or DB.')),
                ('is_app_admin', models.BooleanField(default=False, help_text='App admin: no quotas, no rate limits, no usage card. Set via admin or DB.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'accounts_customuser',
            },
        ),
    ]
