# Generated by Django 5.0.1 on 2026-04-09 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusagelog',
            name='ingest_item',
            field=models.ForeignKey(blank=True, help_text='Related ingest item (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_usage_logs', to='ingestion.ingestitem'),
        ),
        migrations.AddField(
            model_name='apiusagelog',
            name='user',
            field=models.ForeignKey(help_text='The user who triggered this API call', on_delete=django.db.models.deletion.CASCADE, related_name='api_usage_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfeatureconfig',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature_config', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='user',
            field=models.OneToOneField(help_text='The user these preferences belong to', on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(help_text='The user this profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersecret',
            name='user',
            field=models.OneToOneField(help_text='The user this secret belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['user', 'created_at'], name='accounts_ap_user_id_bed36f_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['service', 'created_at'], name='accounts_ap_service_0d0d6d_idx'),
        ),
    ]
