# Generated by Django 5.0.1 on 2026-04-09 14:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GigoUserState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consecutive_low_count', models.PositiveIntegerField(default=0)),
                ('alert_pending', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gigo_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gigo_gigouserstate',
            },
        ),
        migrations.CreateModel(
            name='GigoEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('audio', 'Audio'), ('text', 'Text')], max_length=20)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('rank', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('ingest_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gigo_entries', to='ingestion.ingestitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigo_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gigo_gigoentry',
                'indexes': [models.Index(fields=['user', 'created_at'], name='gigo_gigoen_user_id_87cf34_idx')],
            },
        ),
        migrations.CreateModel(
            name='GigoNudgeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigo_nudge_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gigo_gigonudgelog',
                'indexes': [models.Index(fields=['user', 'created_at'], name='gigo_gigonu_user_id_be685e_idx')],
            },
        ),
    ]
